import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  permissionText: {
    fontSize: 16,
    textAlign: 'center',
    color: '#666',
  },
  loadingContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  waypointsContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 120 : 110,
    left: 16,
    right: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  waypointsScrollContent: {
    paddingHorizontal: 4,
  },
  waypointItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginHorizontal: 4,
    maxWidth: 200,
  },
  waypointNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1a73e8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  waypointNumberText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  waypointName: {
    flex: 1,
    fontSize: 14,
    color: '#000000',
    marginRight: 8,
  },
  removeWaypointButton: {
    padding: 4,
  },
  etaContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 180 : 170,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 10,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  etaContainerOffRoute: {
    backgroundColor: 'rgba(255, 235, 235, 0.9)',
    borderColor: '#ff4444',
    borderWidth: 1,
  },
  etaContent: {
    flex: 1,
  },
  etaText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a73e8',
  },
  etaTextOffRoute: {
    color: '#ff4444',
  },
  offRouteText: {
    fontSize: 14,
    color: '#ff4444',
    marginTop: 4,
  },
  voiceButton: {
    padding: 8,
    marginLeft: 8,
  },
  errorContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 180 : 170,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 10,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  errorText: {
    flex: 1,
    fontSize: 16,
    color: '#ff4444',
  },
  retryButton: {
    padding: 8,
  },
  retryButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1a73e8',
  },
}); 